/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 tasktopia.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import tasktopia from "./tasktopia.glb";
import { useFrame } from "@react-three/fiber";

export function Tasktopia(props) {
    const { nodes, materials } = useGLTF(tasktopia, "/draco-gltf");
    const modelRef = useRef();

    useFrame(({ clock }) => {
        const time = clock.getElapsedTime();
        if (modelRef.current) {
            modelRef.current.position.y = -2 + Math.sin(time) * 0.1;
        }
    });

    return (
        <group {...props} dispose={null} ref={modelRef}>
            <group name="iphonex" position={[0, 1.563, 0]}>
                <mesh
                    name="Circle038"
                    geometry={nodes.Circle038.geometry}
                    material={materials["FrameGrey.001"]}
                />
                <mesh
                    name="Circle038_1"
                    geometry={nodes.Circle038_1.geometry}
                    material={materials["Front.001"]}
                />
                <mesh
                    name="Circle038_2"
                    geometry={nodes.Circle038_2.geometry}
                    material={materials["Antennaline.001"]}
                />
                <mesh
                    name="Circle038_3"
                    geometry={nodes.Circle038_3.geometry}
                    material={materials["BackGrey.001"]}
                />
                <mesh
                    name="Circle038_4"
                    geometry={nodes.Circle038_4.geometry}
                    material={materials["Rubber.001"]}
                />
                <mesh
                    name="AntennaLineBottom001"
                    geometry={nodes.AntennaLineBottom001.geometry}
                    material={materials["Antennaline.001"]}
                    position={[0, -2.676, 0]}
                />
                <mesh
                    name="AntennaLineTop001"
                    geometry={nodes.AntennaLineTop001.geometry}
                    material={materials["Antennaline.001"]}
                    position={[0, 0.018, 0]}
                />
                <mesh
                    name="AppleLogo001"
                    geometry={nodes.AppleLogo001.geometry}
                    material={materials["AppleLogo.001"]}
                    position={[0.171, 0.521, -0.079]}
                />
                <mesh
                    name="BackCameraBottomGreyRing001"
                    geometry={nodes.BackCameraBottomGreyRing001.geometry}
                    material={materials["BackCaneraGrayRIng.002"]}
                    position={[0.702, 0.884, -0.094]}
                />
                <mesh
                    name="BackCameraTopGreyRing001"
                    geometry={nodes.BackCameraTopGreyRing001.geometry}
                    material={materials["BackCaneraGrayRIng.002"]}
                    position={[0.702, 1.178, -0.094]}
                />
                <mesh
                    name="BackCameraBottomLens001"
                    geometry={nodes.BackCameraBottomLens001.geometry}
                    material={materials["Lens.001"]}
                    position={[0.702, 0.884, -0.083]}
                />
                <mesh
                    name="BackCameraTopLens001"
                    geometry={nodes.BackCameraTopLens001.geometry}
                    material={materials["Lens.001"]}
                    position={[0.702, 1.178, -0.083]}
                />
                <mesh
                    name="BackCameraP1001"
                    geometry={nodes.BackCameraP1001.geometry}
                    material={materials["Black.015"]}
                    position={[0.705, 1.027, -0.095]}
                />
                <mesh
                    name="CameraBump001"
                    geometry={nodes.CameraBump001.geometry}
                    material={materials["Frame.001"]}
                    position={[0.704, 1.036, -0.079]}
                />
                <mesh
                    name="FlashBG001"
                    geometry={nodes.FlashBG001.geometry}
                    material={materials["PinkFlash.002"]}
                    position={[0.705, 1.027, -0.093]}
                />
                <mesh
                    name="FrontCameraContainer001"
                    geometry={nodes.FrontCameraContainer001.geometry}
                    material={materials["FrontCameraBlack.002"]}
                    position={[0.335, 1.323, 0.08]}
                />
                <mesh
                    name="FrontSpeakerBG001"
                    geometry={nodes.FrontSpeakerBG001.geometry}
                    material={materials["FrontSpeaker.001"]}
                    position={[0.156, 1.321, 0.077]}
                />
                <mesh
                    name="iPhoneLogo001"
                    geometry={nodes.iPhoneLogo001.geometry}
                    material={materials["iPhoneLogo.001"]}
                    position={[0.2, -1.175, -0.079]}
                />
                <mesh
                    name="MuteSwitch001"
                    geometry={nodes.MuteSwitch001.geometry}
                    material={materials["FrameGrey.001"]}
                    position={[-0.65, 0.92, 0.009]}
                />
                <group name="PowerButton001" position={[0.97, 0.562, -0.004]}>
                    <mesh
                        name="Circle032"
                        geometry={nodes.Circle032.geometry}
                        material={materials["FrameGrey.001"]}
                    />
                    <mesh
                        name="Circle032_1"
                        geometry={nodes.Circle032_1.geometry}
                        material={materials["Frame.001"]}
                    />
                </group>
                <mesh
                    name="VolumeButtons001"
                    geometry={nodes.VolumeButtons001.geometry}
                    material={materials["FrameGrey.001"]}
                    position={[-0.658, 0.208, -0.002]}
                />
            </group>
            <mesh
                name="Plane001"
                geometry={nodes.Plane001.geometry}
                material={materials["BackCaneraGrayRIng.002"]}
                position={[0.189, 0.287, 0]}
            />
            <mesh
                name="Plane"
                geometry={nodes.Plane.geometry}
                material={materials["Material.005"]}
            />
            <mesh
                name="Sparrow_LOD1"
                geometry={nodes.Sparrow_LOD1.geometry}
                material={materials.M_Sparrow}
                position={[0.769, -0.345, -0.265]}
                scale={0.4}
            />
            <mesh
                name="Inkfish_LOD0"
                geometry={nodes.Inkfish_LOD0.geometry}
                material={materials.M_Inkfish}
                position={[0.757, 2.723, -0.108]}
                scale={0.4}
            />
            <mesh
                name="Pudu_LOD1"
                geometry={nodes.Pudu_LOD1.geometry}
                material={materials["M_Pudu.001"]}
                position={[-0.893, -0.29, 0.686]}
                scale={0.4}
            />
        </group>
    );
}

useGLTF.preload(tasktopia);
