/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 pokegen.glb -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import pokegen from "./pokegen.glb";
import { useFrame } from "@react-three/fiber";

export function Pokegen(props) {
    const { nodes, materials } = useGLTF(pokegen, "/draco-gltf");
    const modelRef = useRef();

    useFrame(({ clock }) => {
        const time = clock.getElapsedTime();
        if (modelRef.current) {
            modelRef.current.position.y = -1.5 + Math.sin(time) * 0.1;
        }
    });

    return (
        <group {...props} dispose={null} ref={modelRef}>
            <group
                name="Cube001"
                position={[-0.606, 1.256, 0.772]}
                scale={[0.677, 1, 1]}
            >
                <mesh
                    name="Cube039"
                    geometry={nodes.Cube039.geometry}
                    material={materials.Base}
                />
                <mesh
                    name="Cube039_1"
                    geometry={nodes.Cube039_1.geometry}
                    material={materials.Pink_Buttons}
                />
                <mesh
                    name="Cube039_2"
                    geometry={nodes.Cube039_2.geometry}
                    material={materials["D-Pad"]}
                />
                <mesh
                    name="Cube039_3"
                    geometry={nodes.Cube039_3.geometry}
                    material={materials["Start-Select_Button"]}
                />
                <mesh
                    name="Cube039_4"
                    geometry={nodes.Cube039_4.geometry}
                    material={materials.Front_Panel}
                />
                <mesh
                    name="Cube039_5"
                    geometry={nodes.Cube039_5.geometry}
                    material={materials.Red_Light}
                />
                <mesh
                    name="Cube039_6"
                    geometry={nodes.Cube039_6.geometry}
                    material={materials.Metal}
                />
                <mesh
                    name="Cube039_7"
                    geometry={nodes.Cube039_7.geometry}
                    material={materials.Power_Switch}
                />
                <mesh
                    name="Cube039_8"
                    geometry={nodes.Cube039_8.geometry}
                    material={materials.Screen}
                />
                <mesh
                    name="Cube039_9"
                    geometry={nodes.Cube039_9.geometry}
                    material={materials.Screen_Edge}
                />
            </group>
            <mesh
                name="Plane"
                geometry={nodes.Plane.geometry}
                material={materials.Decal_02}
                position={[-1.039, -0.559, 0.783]}
                rotation={[-Math.PI, 0, Math.PI / 2]}
                scale={[0.202, 0.004, 0.82]}
            />
            <mesh
                name="Plane001"
                geometry={nodes.Plane001.geometry}
                material={materials.Decal_01}
                position={[0.045, 2.4, 1.778]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.284, 0.001, 0.149]}
            />
            <mesh
                name="Plane002"
                geometry={nodes.Plane002.geometry}
                material={materials.Decal_01}
                position={[0.071, -0.583, 1.662]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.844, 0.002, 0.443]}
            />
            <mesh
                name="Plane003"
                geometry={nodes.Plane003.geometry}
                material={materials.Decal_01}
                position={[0.022, 3.155, 0.622]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.334, 0.001, 0.175]}
            />
            <mesh
                name="Plane004"
                geometry={nodes.Plane004.geometry}
                material={materials.Decal_03}
                position={[-1.043, 2.202, 0.771]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[0.095, 0.005, 0.396]}
            />
            <group
                name="Plane005"
                position={[0.016, 3.122, -0.208]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.075, 0, 0.02]}
            >
                <mesh
                    name="Plane009"
                    geometry={nodes.Plane009.geometry}
                    material={materials.Blue_Line}
                />
                <mesh
                    name="Plane009_1"
                    geometry={nodes.Plane009_1.geometry}
                    material={materials.Red_Line}
                />
            </group>
            <mesh
                name="Plane006"
                geometry={nodes.Plane006.geometry}
                material={materials.On_off}
                position={[0.045, 3.497, 1.626]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.284, 0.001, 0.149]}
            />
            <mesh
                name="Plane007"
                geometry={nodes.Plane007.geometry}
                material={materials.Phones}
                position={[0.038, -0.965, 0.884]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.224, 0.001, 0.118]}
            />
            <mesh
                name="Plane008"
                geometry={nodes.Plane008.geometry}
                material={materials.Rear_text}
                position={[-1.157, 1.738, 0.702]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
                scale={[0.766, 0.002, 0.813]}
            />
            <mesh
                name="Plane010"
                geometry={nodes.Plane010.geometry}
                material={materials.D_Pad_Normal}
                position={[0.149, 0.397, 1.468]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={[0.117, 0.001, 0.168]}
            />
            <group name="Cube" position={[-0.8, 2.506, 0.778]} scale={0.557}>
                <mesh
                    name="Cube002"
                    geometry={nodes.Cube002.geometry}
                    material={materials.Cart}
                />
                <mesh
                    name="Cube002_1"
                    geometry={nodes.Cube002_1.geometry}
                    material={materials.Sticker}
                />
                <mesh
                    name="Cube002_2"
                    geometry={nodes.Cube002_2.geometry}
                    material={materials.NormalMap}
                />
            </group>
        </group>
    );
}

useGLTF.preload(pokegen);
